### ISSUE TITLE
Bug occuring during install script of 3rd party debian based image system. DietPi >ONTO> Libre AML-S905X-CC i.e. Rasp Pi 3

### ISSUE THREAD

**Issue by ohsevin** [MichaIng/DietPi#5817] opened 2022-10-17 17:25 UTC
#### Details:
- Date           | Mon Oct 17 17:23:15 UTC 2022
- Bug report     |
- DietPi version | v8.9.2 (MichaIng/master)
- Image creator  |
- Pre-image      |
- Hardware       |  (ID=)
- Kernel version | `Linux raspberrypi 5.19.15-04011-g49dca1c53e48 #1 SMP PREEMPT Fri Oct 14 00:20:35 UTC 2022 aarch64 GNU/Linux`
- Distro         |  (ID=)
- Command        | `sed -i /^[[:blank:]]*dtoverlay=rpivid-v4l2$/d /boot/config.txt`
- Exit code      | 4
- Software title | DietPi-Set_hardware
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
sed: couldn't open temporary file /boot/sedIMVGyn: Read-only file system
```

**Comment by Joulinar** [comment] 2022-10-17 17:33
Duplicate of #5816

**Closed as completed** 2022-10-17 17:33 UTC
Labels: Duplicate
