### ISSUE TITLE
DietPi-Software | Add Grocy, ERP beyond your fridge, a complete household management solution

### ISSUE THREAD

**Issue by LexiconCode** [MichaIng/DietPi#3437] opened 2020-03-24 15:05 UTC
#### Formal software information
- Software title | Grocy
- Short description | ERP beyond your fridge a complete household management solution
- Official URL (if available) | https://grocy.info/
- GitHub URL (if available) | https://github.com/grocy/grocy
- (Official) install documentation | https://grocy.info/links, https://github.com/grocy/grocy#how-to-install

#### Are there similar/alternative software titles available with DietPi-Software?
No alternatives to my knowledge

#### What makes your requested software better than the above solutions, if available?
An actively maintained open-source project that allows you to manage your household much like nextcloud manages your data.

#### How can DietPi make the installation easier or compatible, than following the install instructions or do APT installation, if available?
The official install uses Docker but there are manual installs provided by the community. Basically it's a Web server with a database.

#### Can you provide the installation steps that you would suggest DietPi-Software to do?
Seems like a pretty straightforward install on a ARM system. Steps are included in the following link.
https://github.com/grocy/grocy/issues/201#issuecomment-487074462

#### Are you willing to help maintaining the software installation, e.g. in case of needed setup changes due to updates etc.? This is not needed, but could speed up our decision to implement it, as man power is always a topic :wink:.
I'm willing to help test but I am unexperienced in bash coding.

**Comment by MichaIng** [comment] 2020-03-24 15:30
@LexiconCode 
Many thanks for your request.

Duplicate of #2885? 😄

**Closed as completed** 2020-03-24 15:31 UTC
Labels: Software request :cd:, Duplicate
