### ISSUE TITLE
v150 breaks vmware image ?

### ISSUE THREAD

**Issue by sosher** [MichaIng/DietPi#960] opened 2017-05-15 18:26 UTC
## If your **Virtual Machine** (VMware/Virtual Box) installation is affected by this, please see the following link for solution:  https://github.com/Fourdee/DietPi/issues/960#issuecomment-302054450

---

Hi, Thanks for dietpi 
my diet pi has been upgraded to version 150 on my vmware workstation , And since then 
I get the following error no matter which script I am running
"this script does not support the virtual machine image"

Is it something I am doing wrong ?
Is it possible to downgrade the version to 145 which worked ?

I managed to send bug report 
Thanks

**Comment by powerzumsel** [comment] 2017-05-16 09:09
dito
same issue to me
no "dietpi-xxxx" working

**Comment by Fourdee** [comment] 2017-05-17 09:23
@sosher 
@powerzumsel 

Thanks for the report 👍 

I'll take a look.

**Comment by Fourdee** [comment] 2017-05-17 09:47
Confirmed on fresh install > v150

**Comment by Fourdee** [comment] 2017-05-17 10:44
RootFS RW func check is the cause, script is terminated/failed due to VM script exclusion:
```
 [Info] Patching 146 to 147

This script does not support the Virtual Machine image.

/DietPi/dietpi/dietpi-drive_manager: line 41: Destroy: command not found
```

**Comment by Fourdee** [comment] 2017-05-17 10:47
This will be prevented in v151 update. Affected systems must use the fix below to resolve.

@sosher
@powerzumsel

### If you experience this issue, please run the following commands to resolve:
```
wget https://raw.githubusercontent.com/Fourdee/DietPi/testing/dietpi/dietpi-drive_manager -O /DietPi/dietpi/dietpi-drive_manager
sed -i 's#"044766be-96ca-491a-a93f-913b75a843bd"#044766be-96ca-491a-a93f-913b75a843bd#g' /etc/fstab
systemctl daemon-reload
reboot
```

**Comment by sosher** [comment] 2017-05-17 11:14
Thank you so much for the quick response and suggested fix.
I will be able to try the fix later today 
Thanks again !!!

**Comment by powerzumsel** [comment] 2017-05-17 11:20
fix is working
thank you very much !!!

**Comment by Fourdee** [comment] 2017-05-17 11:26
@sosher 
@powerzumsel 
Thanks guys 👍 

Marking as completed.

I'll try and get v151 pushed out within the next few days, to prevent this occurring during v150 update.

**Closed as completed by Fourdee** 2017-05-17 11:26 UTC
Labels: Bug :lady_beetle:, x86_64 VM, Priority :high_brightness:, Solution available :clinking_glasses:
