### ISSUE TITLE
New commands (dietpi-ddns, dietpi-vpn) do not start from commandline

### ISSUE THREAD

**Issue by maartenlangeveld** [MichaIng/DietPi#4317] opened 2021-04-29 17:18 UTC
New commands (dietpi-ddns, dietpi-vpn) do not start from commandline are not recognised.
They do start via dietpi-launcher menu.

```
root@M-DNS:/# dietpi-ddns
-bash: dietpi-ddns: command not found
```

```
root@M-DNS:/# dietpi-vpn
-bash: dietpi-vpn: command not found
```

**Comment by Joulinar** [comment] 2021-04-29 17:20
Did you reboot your system after update?

**Comment by maartenlangeveld** [comment] 2021-04-29 17:24
No... will try

**Comment by MichaIng** [comment] 2021-04-29 17:29
Alternatively `. /etc/bashrc.d/dietpi.bash` to load the new aliases.

**Comment by Joulinar** [comment] 2021-04-29 17:32
Or logout/login

**Comment by maartenlangeveld** [comment] 2021-04-29 17:34
Thanks!

**Comment by Joulinar** [comment] 2021-04-29 17:36
Is it working now?

**Comment by maartenlangeveld** [comment] 2021-04-29 18:12
Yes! Thanks for the great work.
I have one question. Using pivpn up until now as openvpn server. Does dietpi-vpn openvpn server as well (or only client?)

**Comment by MichaIng** [comment] 2021-04-29 18:15
It's a client only so far. Maybe we can extend it to configure a server as well by times, adding a client config/revocation UI. But first of all we'll extend the client functionality, adding more providers, free port choice, server rotation and such 😃.

**Comment by Joulinar** [comment] 2021-04-29 18:17
Going to close this as the issue is fixed

**Closed as completed by Joulinar** 2021-04-29 18:17 UTC
