### ISSUE TITLE
[bug] infinite "command not found errors" when plugging in a usb to rpi3b+ when using usb boot

### ISSUE THREAD

**Issue by t3dium** [MichaIng/DietPi#5850] opened 2022-10-30 17:39 UTC
![image](https://user-images.githubusercontent.com/83690012/198892488-4e42424f-5f36-4751-8240-d6008a68cb0b.png)

~~I can't reproduce this bug after i re-flashed the usb with dietpi and reinstalled, it only happened once randomly~~

Edit: this issue only appears to be caused when plugging in an extra usb into the raspberry pi, if using usb boot. The OS stops working entirely. Also attached a pic of a docker install, and it failing when inserting a usb midway:

![image](https://user-images.githubusercontent.com/83690012/198893397-81808278-a018-479f-a839-b364e7d09e8e.png)

**version:** latest mainbranch 
**hardware:** rpi3b+

**Comment by MichaIng** [comment] 2022-10-30 18:01
It looks like the filesystem is corrupted, missing basic system commands. Run `fsck` on it from a different Linux system and you'll find a lot of filesystem errors.

Is it a 2.5" drive and do you power it via dedicated PSU or through USB only? The letter won't work reliably on RPi USB ports and causes exactly such kind of errors. That the issue is triggered when attaching another USB device is another indicator to USB power issues.

**Comment by t3dium** [comment] 2022-10-30 18:14
> Is it a 2.5" drive and do you power it via dedicated PSU or through USB only? The letter won't work reliably on RPi USB ports and causes exactly such kind of errors. That the issue is triggered when attaching another USB device is another indicator to USB power issues (the max USB power is shared across all ports).

Just two flash drives, using the raspberry pi's power.

**Comment by MichaIng** [comment] 2022-10-30 18:19
Please check:
```sh
dmesg -l emerg,alert,crit,err
```
for kernel errors.

**Comment by t3dium** [comment] 2022-10-30 18:27
> Please check:
> 
> ```shell
> dmesg -l emerg,alert,crit,err
> ```
> 
> for kernel errors.

I'll check this soon when i boot into the usb again, but i dont think it'd work since no commands were previously working. They were all returning input/output error.

**Comment by MichaIng** [comment] 2022-10-30 18:30
Then you need to reflash the image, boot without the second USB device attached. Then attach/mount the second USB device, check for kernel errors, in case run some updates/do some I/O and check for kernel errors again. This would be to verify that it's a powering issue, or in case whether it's another specific issues with those drives or their combination somehow.

**Comment by MichaIng** [comment] 2022-12-30 04:39
Marking this as closed for now. Feel free to reopen if the issue persists and you find time to further debug.

**Closed as completed by MichaIng** 2022-12-30 04:39 UTC
Labels: Raspberry Pi
