### ISSUE TITLE
RPi | LXDE issues

### ISSUE THREAD

**Issue by gammaleak** [MichaIng/DietPi#1558] opened 2018-02-26 02:56 UTC
#### Required Information:
- DietPi Version | ```cat /DietPi/dietpi/.version```? v6.2
- SBC Device (EG: RPi 3)? RPi3
- Power supply used (EG: 5v 1A RAVpower)? 5V 2.5A
- SD card used (EG: Sandisk ultra)? LoveRPi branded
- Distro (EG: Jessie) | ```uname -a```? Stretch

#### Additional Information (if applicable):
- Software title? PCManFM
- Can this issue be replicated on a fresh installation of DietPi? Yes

#### Expected behaviour:

If you install LXDE, the basic applications that come with it should all have fully functioning icons.

#### Actual behaviour:

PCManFM has broken icons for the "View" toggles (i.e., "Large Icons," "Small Icons," "Detailed List," etc.)

#### Steps to reproduce:

1. Install DietPi with LXDE
2. Launch LXDE
3. Observe broken icons in toolbar

#### Did you submit a ```dietpi-bugreport```?

I didn't submit one.

#### Extra details:

I tried adding a new icon set (Oxygen) from the repository, but that didn't fix the issue. Seems like maybe PCManFM is expecting to find those icons somewhere specific and they aren't there?

**Comment by MichaIng** [comment] 2018-02-26 11:21
@gammaleak  
Thanks for your report, I will try to replicate on VM.

**Comment by MichaIng** [comment] 2018-02-26 19:28
@gammaleak 
I couldn't replicate on Stretch VM. LXDE and PCManFM working and icons looking as they should.

Do you see any error messages within journalctl? Don't know where PCManFM/Openbox would drop their error messages actually, didn't use a desktop for a long time 😅.

In case someone with testing RPi has to try replicate.

**Comment by Fourdee** [comment] 2018-02-27 16:25
RPi 3 Stretch LXDE fresh install:
- Other devices are fine, RPi issue only.
- 🈴 Confirmed
![image](https://user-images.githubusercontent.com/7077026/36740596-ce44f274-1bda-11e8-8dbf-dd7b5e64b46a.png)

**Comment by Fourdee** [comment] 2018-02-27 16:43
```
** (pcmanfm:9863): WARNING **: The directory '/root/Templates' doesn't exist, ignoring it

(pcmanfm:9863): Gtk-CRITICAL **: IA__gtk_menu_shell_insert: assertion 'GTK_IS_MENU_SHELL (menu_shell)' failed
```

```
root@DietPi:~# dpkg -l | grep icon
ii  adwaita-icon-theme             3.22.0-1+deb9u1              all          default icon theme of GNOME
ii  gtk-update-icon-cache          3.22.11-1+rpi3               armhf        icon theme caching utility
ii  hicolor-icon-theme             0.15-1                       all          default fallback theme for FreeDesktop.org icon themes
ii  libtext-iconv-perl             1.7-5+b8                     armhf        converts between character sets in Perl
ii  lxde-icon-theme                0.5.1-2                      all          LXDE standard icon theme
```

- Favorites tab missing aswell.
- 🈴 "Customize look and appearance" hangs LXDE over VNC, terminate ```dbus-launch``` resolves. 
- 🈯️ Adwaita/PiX resolves broken LXDE toolbar icons. 🈺 Reset after reboot/service restart
```
root@DietPi:~# cat .gtkrc-2.0
# DO NOT EDIT! This file will be overwritten by LXAppearance.
# Any customization should be done in ~/.gtkrc-2.0.mine instead.

include "/root/.gtkrc-2.0.mine"
gtk-theme-name="Clearlooks"
gtk-icon-theme-name="Adwaita"
gtk-font-name="Sans 10"
gtk-cursor-theme-size=18
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle="hintslight"
gtk-xft-rgba="rgb"
```

```
cat << _EOF_ > ~/.gtkrc-2.0.mine
gtk-theme-name="Clearlooks"
gtk-icon-theme-name="Adwaita"
gtk-font-name="Sans 10"
gtk-cursor-theme-size=18
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle="hintslight"
gtk-xft-rgba="rgb"
_EOF_
```

**Comment by Fourdee** [comment] 2018-03-25 17:03
Notes:
- As far as I can tell, the only reason this may be occurring from our side, is:
-- due to removal of ```dbus``` in PREP. However, it is installed via APT during LXDE install. Is it possible removing Dbus initially is the cause?
I'll need to confirm/exclude this by doing a PREP without removal of DBUS and retest.

**Comment by Fourdee** [comment] 2018-05-18 20:48
Tests:
- Debian pcmanfm 🈯️ 
```
wget http://ftp.us.debian.org/debian/pool/main/p/pcmanfm/pcmanfm_1.2.5-3_armhf.deb
dpkg -i *.deb
```

RPi version of ```pcmanfm``` is the issue, most likely customized towards the RPi desktop, either way, we'll pull in the Debian version to resolve.

**Comment by Fourdee** [comment] 2018-05-18 21:07
```lxappearance``` still an issue, hangs on open with spawned ```dbus-launch``` process:
Terminate ```dbus-launch``` and it then runs.
```
root@DietPi:~# dpkg -l | grep lx | grep rpi
ii  libgl1-mesa-glx:armhf          13.0.6-1+rpi2                armhf        free implementation of the OpenGL API -- GLX runtime
ii  lxde                           9+rpi1                       all          Metapackage for LXDE
ii  lxde-core                      9+rpi1                       all          Metapackage for the LXDE core
ii  lxinput                        0.3.5-1+rpi4                 armhf        LXDE keyboard and mouse configuration
ii  lxpanel                        0.9.3-1+rpi6                 armhf        LXDE panel
ii  lxpanel-data                   0.9.3-1+rpi6                 all          LXDE panel (data files)
ii  lxterminal                     0.3.0-2+rpi1                 armhf        LXDE terminal emulator

root@DietPi:~# dpkg -l | grep openbox | grep rpi
ii  libobrender32v5                3.6.1-4+rpi6                 armhf        rendering library for openbox themes
ii  libobt2v5                      3.6.1-4+rpi6                 armhf        parsing library for openbox
ii  openbox                        3.6.1-4+rpi6                 armhf        standards-compliant, fast, light-weight and extensible window manager

```

**Comment by Fourdee** [comment] 2018-05-21 19:30
Completed, new ticket for the other issues with lxappearance:
https://github.com/Fourdee/DietPi/issues/1791#issue-325031923

**Comment by puccaso** [comment] 2018-11-02 07:42
hey guys - you know, im having the same issue.
i've documented the issue on raspberry pi forums, https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=225936&p=1387128#p1387128

the PIX icon theme works, but nothing else.

**Comment by puccaso** [comment] 2018-11-02 07:44
![image](https://user-images.githubusercontent.com/3234729/47899898-eb4b0380-de72-11e8-8ab0-77fbf82278b0.png)
![image](https://user-images.githubusercontent.com/3234729/47899909-f140e480-de72-11e8-9bf1-efa97de9fc75.png)
![image](https://user-images.githubusercontent.com/3234729/47899918-f6059880-de72-11e8-85b7-de2e1f8c7dce.png)
Here is my current output.
im on the most recent raspbian - how might i patch the rasbpian code with the Dietpi fix?

**Comment by Fourdee** [comment] 2018-11-02 21:50
@puccaso 

Hi, 

We forgot to hold the APT package during install (fixed in v6.18). Raspbian repo updates will replace the pcmanfm package and broken icons will re-appear.

Workaround, is to reinstall the Debian repo (mirrored on our site) pcmanfm with working icons:
```
wget https://dietpi.com/downloads/binaries/all/pcmanfm_1.2.5-3_armhf.deb
dpkg -i *.deb
```

**Comment by puccaso** [comment] 2018-11-03 14:41
hello @Fourdee , 

thanks for getting back to me, 

yea, that just segments for me,
im looking in the deb package itself for what is different.. 
what exactly has been/needs to be change in the source for the RPI guys, maybe i can follow this up with them..

**Comment by MichaIng** [comment] 2018-11-03 14:44
@puccaso 
This would be great. Always better to solve this dev/maintainer side instead of keeping an unideal workaround.

**Comment by MichaIng** [comment] 2019-10-08 08:28
Same issue present on current current RPi Buster image.

**Comment by irenegr** [comment] 2019-10-10 17:49
Same problem on Raspbian Buster. I found a workaround (?): Pcmanfm->Edit->Preferences->Layout->disable "Display simplified user interface and menus".
Toolbar icons are back again (Papirus icons).

**Comment by MichaIng** [comment] 2020-08-31 17:09
Similar issue with lxpanel from RPi repo where the LXDE menu icon is missing. Very strange thing there, one can open the panel menu settings and the correct icon is pre-selected and exists. One can change padding there, changing it back and forth makes the correct space is taken by the menu, while before only a minimal very small space is reserved, so somehow the icon info is used, but the icon image itself still does not appear. Opening it with image viewer works fine.

I installed `pixflat-icons` icon theme (alternatively `rpd-icons`), just to test around some solution (better then using Debian/Raspbian packages and breaking the official RPi desktop by this, if someone wants to install it) and switching to this icon theme restores the icons in PCManFM, but not the menu icon... Messy RPi desktop packages I have to say, I'll go on playing around with it to get it running without the need to manually change settings.

**Comment by MichaIng** [comment] 2020-08-31 17:43
There is a Raspberry Pi UI (desktop) orga with all related repos on GitHub: https://github.com/raspberrypi-ui/
Didn't know that.

**Comment by MichaIng** [comment] 2020-08-31 17:51
@irenegr 
Disabling "`Display simplified user interface and menus`" does not show the toolbar icons, it simply hides the additional icons that lack an image. Those additional buttons provided by this setting allow to change the view of current directory items and open a new PCManFM window. Checking now whether Raspbian/Debian version of PCManFM as well doesn't have these icons + this setting disabled by default or if they have those icons for some reason.

**Comment by MichaIng** [comment] 2020-08-31 18:28
Using Raspbian or Debian package on Buster does not work at all, it just pops up for a microsecond and fails/exits immediately without any error message (nothing when started from console as well), I just tested what was reported here already: https://github.com/MichaIng/DietPi/issues/3570#issuecomment-678048253 _(same with the package from Debian repo)_
_________
Indeed the option mentioned above is an RPi addition and does not exist on Debian: https://github.com/raspberrypi-ui/pcmanfm-buster/commit/89850963227503e7ad832d0fd0376c04e174d601
Also verified on Debian LXDE install.

There are quite a few more issues with this desktop when not configured and paired with the official RPi desktop it seems. Also the panel icons on RPi are slightly smaller, but scaled down badly with quality loss, no sharp anymore. Of course the hanging lxappearance when opening in TigerVNC is bad as well. I'll see if replacing all LXDE/desktop related packages together solves the issue(s).
_________
Okay after reverting nearly everything that is anyhow related to LXDE, Openbox, PCManFM, including libraries, hanging lxappearance is not resolved and PCManFM does not start up at all. Only the missing menu icon could be resolved. The problem with replacing + blocking single packages is that we never when when we break any other APT install with this. I'd rather report all three issues to RPi repo (now that we know them) and have them solved there, something all RPi users (with vanilla LXDE) benefit from instead of ours only.

**Comment by MichaIng** [comment] 2020-09-11 16:55
Lonely issue about the missing icons on PCManFM: https://github.com/raspberrypi-ui/pcmanfm-buster/issues/2
Issue about hanging LXAppearance on TigerVNC sessions: https://github.com/RPi-Distro/repo/issues/202
Issue about missing menu icon + blurry application icons on panel: https://github.com/raspberrypi-ui/lxpanel-buster/issues/3

**Comment by MichaIng** [comment] 2020-09-12 15:44
Sad, no chance to work with, no aim/too much work to make the RPi repo LXDE packages compatible with native LXDE installs (`apt install lxde` instead of `apt install raspberrypi-ui-mods`) and they seem to be so much different from upstream versions so that merging the reasonable changes will never happen. So we have to accept the fact that all raspberrypi-ui packages are working with complete RPi default desktop only. I'll try to replicate some of the issues with native RPi desktop now ~(the blurry icons are almost certainly an issue there as well, simply no recognised due to missing comparison) to have any chance for attention~. As workaround at least we know the packages that we need to pin for now.
Another thing is to request the separation of ui components from main repo (as it was until Stretch) that that RPi kernel/firmware can be used without breaking LXDE and probably other desktops/elements.
_______
Okay, RPi desktop is VERY different. lxappearance starts fine there but it has no effect, selecting themes or icon sets or cursor icons has no effect, nothing is applied or stored. It has an own appearance tool instead. The menu icon is a dedicated overlay, it cannot be changed, the setting just has the dummy entry "start-here", no icon path and no effect.

**Comment by MichaIng** [comment] 2020-09-24 11:59
Workaround implemented: https://github.com/MichaIng/DietPi/commit/129673983a126ece2ef541114b2e22301aa87087
________
Final request to again separate the RPi desktop from the main repository component (like it was until including Stretch): https://github.com/RPi-Distro/repo/issues/203
I see this the last chance to have a reliable native LXDE experience on RPi, as maintaining a pin list is at best fragile and while fixing one thing we might create other issues, e.g. due to changing package dependencies over overlaps between desktop and X server packages.
________
A complete different approach would be to simply replace the LXDE desktop with the native RPi LXDE desktop 🤔. But I'm no fans of providing larger different solutions on different machines as this as well means doubled maintenance effort.

**Comment by MichaIng** [comment] 2020-09-30 17:56
Another day of testing and debugging and finally I found a solution for hanging `lxappearance` on TigerVNC LXDE sessions. Don't ask me for details why this is required in this specific circumstance, but [apt install dbus-user-session](https://packages.debian.org/en/buster/dbus-user-session) solves the issue.
- Basically **without** this package, when starting an X session, a `dbus-daemon` + `dbus-launch` instance is started with a specific ID. On `lxappearance` start, the exact same `dbus-launch` (same cmd options, same ID) is attempted to be started again, which hangs. Only a single instance is allowed, which is somewhat explained in the package details.
- **With** this package, the `dbus-daemon` instance is started a `systemd --user` child process, the `dbus-launch` is not visible. This seems to allow the concurrent `dbus-launch` instance(s) then.

Here the different process hierarchy can be seen:
![dbus](https://user-images.githubusercontent.com/28480705/94722562-c52c8780-0357-11eb-95ce-736389079751.png)
__________
~Now the question is why this is only an issue on RPi 🤔.~
EDIT: Not an RPi issue, just verified the same on VM. Not sure why this has not been found before.

**Comment by Joulinar** [comment] 2020-10-01 20:34
@MichaIng 
As I'm not sure, will the missing menu item be fixed in 6.33 as well? I know we discussed it on the RPi 64bit issue already and you provided a workaround https://github.com/MichaIng/DietPi/issues/3570#issuecomment-675269253.

I'm asking because we have a new report on our forum https://dietpi.com/phpbb/viewtopic.php?p=27620#p27620

**Comment by MichaIng** [comment] 2020-10-01 20:46
Yes I applied the workaround already:
- https://github.com/MichaIng/DietPi/blob/dev/dietpi/dietpi-software#L3000-L3008
- Changelog: https://github.com/MichaIng/DietPi/blob/dev/CHANGELOG.txt#L27

**Comment by MichaIng** [comment] 2020-10-02 15:43
Okay all done that we can do our side. I'll leave it marked as workaround, as this is what it is, sadly not more.

**Closed as completed by MichaIng** 2020-10-02 15:43 UTC
Labels: Raspberry Pi, External bug :lady_beetle:, Workaround available :ok:
