### ISSUE TITLE
bug report 0013ef1019eb-0 : Can't connect deluge deamon on windows client remote

### ISSUE THREAD

**Issue by Nibeck1309** [MichaIng/DietPi#95] opened 2015-10-16 16:22 UTC
I can't connect to my RPI2 dietpi V97 deluge with my Windows 10 deluge client.

When I configure the client, the deamon appear not start
I can connect to the webui

**Comment by Fourdee** [comment] 2015-10-17 13:38
Hi,

Thanks for the bug report.
I'am unable to replicate your issue.
![untitled](https://cloud.githubusercontent.com/assets/7077026/10558971/acce4a98-74dc-11e5-93c1-d7bef6fbc228.jpg)

Have you tried restarting the service as per the 1st run guide? http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=5&start=10#p61

dietpi-services restart

**Comment by Nibeck1309** [comment] 2015-10-20 06:31
Hy,

I do a clen install of dietpi, install deluge from dietpi-software, reboot, dietpi-service restart. 
I can connect to deluge from windows deluge client.
On next reboot i can't connect. The deluge deamon appear not run on windows deluge

**Comment by Fourdee** [comment] 2015-10-20 11:25
I will run another test today on my RPi v1 and Wheezy (which i believe, from your bug report is your system setup) using your steps to try and replicate the issue.

I'll be in touch.

**Comment by Nibeck1309** [comment] 2015-10-20 15:28
Hy,

I have news information,

When I reboot my RPI, on next reboot I can't connect to deluge with windows deluge client.
But if after I reboot Dietpi, i executed dietpi-service restart, I can connect to deluge....

Why I do execut dietpi-service restart for deluge works after i reboot Dietpi ?

**Comment by Fourdee** [comment] 2015-10-20 18:11
Thanks for the update. 
I'am just waiting for my RPi v1 to install deluge (busy day), then i'll take a look.

**Comment by Fourdee** [comment] 2015-10-20 18:42
Using client: 1.3.12-1 & Python 2.7
http://download.deluge-torrent.org/windows/py2.7/deluge-1.3.12-1-win32-py2.7-setup.exe

After reboot, unable to connect deluge client:
- Only occurs on Wheezy. Jessie is fine.
- Log file is identical, after reboot [deluge_reboot.txt](https://github.com/Fourdee/DietPi/files/17056/deluge_reboot.txt) and restart of services [deluge_after.txt](https://github.com/Fourdee/DietPi/files/17055/deluge_after.txt) . Only warnings are for fast resume file, no other errors to go on.
- dietpi-services is called in rc.local (last item).
-  Web UI is not affected, runs as it should after reboot.

Its possible the issue is caused by Deluge itself as the logfiles provide no info, deluge tells us everything is ok and running.

Resolution options:
- Please try the DietPi Jessie image (which doesnt cause this issue). http://dietpi.com/downloads/DietPi_RPi-(Jessie).7z
- Manually run dietpi-services restart after boot/login.

**Comment by Fourdee** [comment] 2015-10-20 18:51
I will close this ticket. Please see my previous post for resolution options.

Please re-open ticket if required.

**Closed as completed by Fourdee** 2015-10-20 18:51 UTC
Labels: Bug :lady_beetle:
