### ISSUE TITLE
DietPi-DriveManager does not auto detect more than one partition on external USB

### ISSUE THREAD

**Issue by RajatNair** [MichaIng/DietPi#540] opened 2016-10-02 08:02 UTC
Hi,

Just wanted to report that the DietPi-DriveManager is only detecting 1st/1 partition from an external USB drive - during initial setup and later while using "refresh" feature. 

I manually mounted the partition onto /mnt/usb_4 and re-ran refresh but "Slot 4" did not get filled (Slots 1 - 3 contained external USB drives with 1 partition)

Additional info - 
Running on OdroidC2 - DietPi v132

**Comment by Fourdee** [comment] 2016-10-02 11:58
@RajatNair 

Thanks for the report.

>  DietPi-DriveManager is only detecting 1st/1 partition

This is by design. 
Its mainly to simplify the user experience. We expect users to use the whole drive (eg: external WD elements) with DietPi.
By adding partition support into `dietpi-drive_manager` it would complicate the interface massively, confusing most users. 
We would also have to generate multiple `/mnt/usb_1p[0-9]` mount points, and add auto mount in fstab for those entries (which adds about 1 second per mount to boot time if unplugged).

Its worth noting that formatting any drive in `dietpi-drive_manager` will clear the partition table. Creating 1 partition for the whole drive.

If you wish to edit multiple partitions, `gparted` is highly recommended for advanced use.

Marking as closed, please reopen if required.

**Closed as completed by Fourdee** 2016-10-02 11:58 UTC
Labels: Question :grey_question:
