### ISSUE TITLE
Jellyfin Transcoding on Bullseye Not Working

### ISSUE THREAD

**Issue by legends2k** [MichaIng/DietPi#4827] opened 2021-10-12 01:54 UTC
JellyFin, with OMX (hardware acceleration) enabled, doesn't play videos that need transcoding.  I get

```
[h264_omx @ 0x2b98870] /opt/vc/lib/libbcm_host.so not found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

As per #4729, I think Bullseye only has `/usr/lib/arm-linux-gnueabihf/libbcm_host.so.0`.  However, `ffmpeg` (shipped with Jellyfin) seems to look for the `.so` in the old `/opt/vc/lib` directory.  Symlinking `libbcm_host.so` in `/opt/vc/lib` led to another error:

```
[h264_omx @ 0x2534870] /opt/vc/lib/libopenmaxil.so not found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

I don't know where to find `libopenmaxil.so`; it's absent in `/usr/lib/arm-linux-gnueabihf`.

Full error log:

```
ffmpeg version 4.3.2-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-2)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --toolchain=hardened --enable-cross-compile --enable-omx --enable-omx-rpi --enable-mmal --arch=armhf --cross-prefix=/usr/bin/arm-linux-gnueabihf-
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[avi @ 0x2b7b4e0] non-interleaved AVI
Input #0, avi, from 'file:/mnt/MyMedia/Animated.avi':
  Metadata:
    encoder         : AVI-Mux GUI 1.17.7, Aug  8 2006  20:59:17
    JUNK            : 
  Duration: 02:04:24.95, start: 0.000000, bitrate: 788 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 608x256 [SAR 1:1 DAR 19:8], 668 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 44100 Hz, stereo, fltp, 112 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (h264_omx))
  Stream #0:1 -> #0:1 (mp3 (mp3float) -> aac (native))
Press [q] to stop, [?] for help
[h264_omx @ 0x2b98870] /opt/vc/lib/libbcm_host.so not found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[aac @ 0x2b8da80] Qavg: 65536.000
[aac @ 0x2b8da80] 2 frames left in the queue on closing
Conversion failed!
```

#### Required Information

- DietPi version
```
G_DIETPI_VERSION_CORE=7
G_DIETPI_VERSION_SUB=6
G_DIETPI_VERSION_RC=2
G_GITBRANCH='master'
G_GITOWNER='MichaIng'
G_LIVE_PATCH_STATUS[0]='not applicable'
G_LIVE_PATCH_STATUS[1]='applied'
G_LIVE_PATCH_STATUS[2]='applied'
G_LIVE_PATCH_STATUS[3]='applied'
G_LIVE_PATCH_STATUS[4]='applied'
```

- Distro version: `bullseye 1`
- Kernel version: `Linux DietPi 5.10.63-v7l+ #1457 SMP Tue Sep 28 11:26:14 BST 2021 armv7l GNU/Linux`
- OS bit width: 32 (deduced from `getconf LONG_BIT`)
- SBC model: RPi 4 Model B (armv7l)
- Power supply used: 5V 1A RAVpower
- SDcard used: SanDisk ultra

**Comment by MichaIng** [comment] 2021-10-12 11:24
The Jellyfin FFmpeg package requires a rebuild as of the libraspberrypi0 changes you linked. Issue has been reported already: https://github.com/jellyfin/jellyfin-ffmpeg/issues/75

I mark this closed as duplicate of: #4821

**Closed as completed by MichaIng** 2021-10-12 11:24 UTC
Labels: Known Issue :bug:, Duplicate, Bullseye
