### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by Xerduntis** [MichaIng/DietPi#6079] opened 2023-01-19 23:12 UTC
#### Details:
- Date           | Fri Jan 20 00:05:28 CET 2023
- Bug report     | bb62600b-252f-4b9c-b88f-4eaf38a07c01
- DietPi version | v8.12.1 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | From scratch
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux RaspberryPi 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `apt-get -y update`
- Exit code      | 255
- Software title | DietPi-Update
#### Steps to reproduce:

1. I simply ran 'dietpi-update' from v8.12.1 to v8.13.2
#### Expected behaviour:

- updating dietpi
#### Actual behaviour:

- I get an error
#### Extra details:

- Reference code: bb62600b-252f-4b9c-b88f-4eaf38a07c01
#### Additional logs:
```
Err:1 https://deb.debian.org/debian bullseye InRelease
  Could not handshake: Error in the pull function. [IP: 2a04:4e42:65::644 443]
Hit:2 https://archive.raspberrypi.org/debian bullseye InRelease
Err:3 https://deb.debian.org/debian bullseye-updates InRelease
  Could not handshake: Error in the pull function. [IP: 2a04:4e42:65::644 443]
Err:4 https://deb.debian.org/debian-security bullseye-security InRelease
  Could not handshake: Error in the pull function. [IP: 2a04:4e42:65::644 443]
Err:5 https://deb.debian.org/debian bullseye-backports InRelease
  Could not handshake: Error in the pull function. [IP: 2a04:4e42:65::644 443]
Reading package lists...
W: Failed to fetch https://deb.debian.org/debian/dists/bullseye/InRelease  Could not handshake: Error in the pull function. [IP: 2a04:4e42:65::644 443]
W: Failed to fetch https://deb.debian.org/debian/dists/bullseye-updates/InRelease  Could not handshake: Error in the pull function. [IP: 2a04:4e42:65::644 443]
W: Failed to fetch https://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Could not handshake: Error in the pull function. [IP: 2a04:4e42:65::644 443]
W: Failed to fetch https://deb.debian.org/debian/dists/bullseye-backports/InRelease  Could not handshake: Error in the pull function. [IP: 2a04:4e42:65::644 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
Sorry if this post is not very helpful, I got this message after aborting the update telling me to post it here

**Comment by Joulinar** [comment] 2023-01-20 01:56
For testing, can you disable IPv6 temporary and try again.

**Comment by Xerdunits** [comment] 2023-01-20 15:33
Hey, thanks for the quick reply!

I just re-ran the update process and it went through without trouble. Sorry that I can't reproduce the problem anymore, but thanks for the help!

I thought this really was something I needed to post here because I got this huge message telling me to and I just wanted to help. Turns out it fixed itself over night like most of the problems...

**Comment by Joulinar** [comment] 2023-01-20 15:37
maybe a temp issue on server side with IPv6. Goot it is fixed now. Going to close the issue.

**Closed as completed by Joulinar** 2023-01-20 15:37 UTC
