### ISSUE TITLE
[FAILED] Unknown install state/First run setup failed

### ISSUE THREAD

**Issue by ghost** [MichaIng/DietPi#4722] opened 2021-09-10 10:01 UTC
#### Details:
- Date           | Fri Sep 10 10:42:59 BST 2021
- DietPi version | v6.33.3 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | Radxa
- Hardware       | ROCK Pi S (aarch64) (ID=73)
- Kernel version | `Linux DietPi 4.4.143-57-rockchip-g4b8d0571d76e #1 SMP PREEMPT Mon Sep 14 10:40:09 UTC 2020 aarch64 `GNU/Linux
- Distro         | buster (ID=5)
- Command        | apt-get -qq upgrade
- Exit code      | 100
- Software title | DietPi-Update
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 35837 files and directories currently installed.)
Preparing to unpack .../rockchip-overlay_2.9_all.deb ...
Unpacking rockchip-overlay (2.9) over (2.7) ...
dpkg: error processing archive /var/cache/apt/archives/rockchip-overlay_2.9_all.deb (--unpack):
 trying to overwrite '/lib/firmware/rockchip/dptx.bin', which is also in package firmware-misc-nonfree 20190114-2
Remove two files, hdmi.rules and hdmi-toggle

Errors were encountered while processing:
 /var/cache/apt/archives/rockchip-overlay_2.9_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by MichaIng** [comment] 2021-09-10 11:03
Many thanks for the report.

It's a duplicate of: #4715
I provided a workaround there and will now report the bug to Radxa.

**Closed as completed** 2021-09-10 11:04 UTC
Labels: External bug :lady_beetle:, Duplicate
