### ISSUE TITLE
DietPi-Software | Chromium: Newest version fails on Tinkerboard

### ISSUE THREAD

**Issue by stogoh** [MichaIng/DietPi#2296] opened 2018-11-27 18:55 UTC
#### Required Information:
- Distro version		| 9.6
- Kernel version		| Linux DietPi 4.4.103+ #1 SMP Fri Jun 22 16:14:49 CST 2018 armv7l GNU/Linux
- SBC device			| Asus Tinker Board (armv7l)
- Power supply used	| 5V 3A
- SDcard used			| SanDisk ultra 16GB

#### Additional Information (if applicable):
- Software title	| Chromium
- The software is a fresh install
- The issure occurs also after reinstall
- ReportID: `d5560227-5006-460e-b79c-632b96af2e01
`
#### Steps to reproduce:
Running `sudo chromium --no-sandbox` or `chromium browser`

#### Expected behaviour:
The chromium brower should start

#### Actual behaviour:
The browser shows up for a short time, but then closed immediately.

#### Extra details:
Console output

```
[4557:4557:1127/200750.582342:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-proce$
[4521:4734:1127/200750.597713:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address t$
Received signal 11 SEGV_MAPERR 000000000000
#0 0x000080f1ebf0 <unknown>
#1 0x000080eab300 <unknown>
#2 0x000080f1eee2 <unknown>
#3 0x000080f1f124 <unknown>
#4 0x0000b2cb4fe0 <unknown>
#5 0x00007fc53fe0 <unknown>
#6 0x00008119cc94 <unknown>
#7 0x000081559916 <unknown>
#8 0x000081e4f6dc <unknown>
#9 0x000081e4f7a8 <unknown>
#10 0x000081e4f87c <unknown>
#11 0x000081e4f904 <unknown>
#12 0x000081e4f936 <unknown>
#13 0x000080df3c88 <unknown>
#14 0x000080df3cc2 <unknown>
#15 0x000080ca7cc0 <unknown>
#16 0x000080cabd14 <unknown>
#17 0x000080cabf82 <unknown>
#18 0x0000800e4ad6 <unknown>
#19 0x000080328836 <unknown>
#20 0x0000800eb182 <unknown>
#21 0x0000800eb66a <unknown>
#22 0x0000800e6776 <unknown>
#23 0x000080c8ae74 <unknown>
#24 0x000080c8b69a <unknown>
#25 0x000080c8fffe <unknown>
#26 0x000080c8ac78 <unknown>
#27 0x00007fad8190 ChromeMain
#28 0x0000b2ca64aa __libc_start_main
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by MichaIng** [comment] 2018-11-29 15:58
@Stogoh
Thanks for your report. We will investigate.

**Comment by stogoh** [comment] 2018-11-29 16:11
@MichaIng 
**Sidenote**
I had the same problem with TinkerOS after `sudo apt-get upgrade`. But when I just use the image which is online and **not** update it, then chromium is working. Maybe some package is getting updated and then does not work anymore.

**Comment by MichaIng** [comment] 2018-11-29 18:10
Thanks for the info. So we need to check which version still works, what changed and what we need to adjust e.g. in xorg.conf to get it running again.

**Comment by Fourdee** [comment] 2018-11-29 21:16
@Stogoh 

Looks like an issue with GPU accell, as a workaround for now, try disabling the glamor driver:
```
mv /etc/X11/xorg.conf.d/20-modesetting.conf /etc/X11/xorg.conf.d/20-modesetting.conf.disable
```

**Comment by stogoh** [comment] 2018-11-29 21:51
I have now disabled the driver, but now it fails to initialize xserver. So I‘m suck in the console right now.

**Comment by Fourdee** [comment] 2018-11-29 21:58
@Stogoh 

Updating our TinkerOS image, i'll take a look in the next hour or two.

**Comment by Fourdee** [comment] 2018-11-30 03:11
Confirmed issue: https://tinkerboarding.co.uk/forum/archive/index.php/thread-1735.html

@Stogoh 
To return X back to working state:
```
mv /etc/X11/xorg.conf.d/20-modesetting.conf* /etc/X11/xorg.conf.d/20-modesetting.conf
```

**Comment by Fourdee** [comment] 2018-11-30 03:20
Still occurs with v67...
```
wget https://snapshot.debian.org/archive/debian-security/20180701T015633Z/pool/updates/main/c/chromium-browser/chromium_67.0.3396.87-1~deb9u1_armhf.deb
dpkg -i *.deb
rm *.deb
```

Same with egl flag removed.

**Comment by Fourdee** [comment] 2018-11-30 06:04
Note to self:
- Image updated to mainline (in testing folder)
- midgard driver with EGL support
- Confirmed Kodi support
- Confirmed Chromium under autostart support
- Do not release until v6.19 is live, due to dev prep'ed and desktop changes

ref: https://github.com/Fourdee/DietPi/commit/fc823eb63c6797cc6fd99ed88d9f6ca01158070d

**Comment by stogoh** [comment] 2018-12-06 18:18
Well. I just updated to the newest version of DietPi and the problem returns again.

**Comment by MichaIng** [comment] 2019-01-05 22:34
@Fourdee 
The new images are in place, if I see right? If still an issue with current Chromium, is there something we can do about running systems? Any chance to update them to mainline kernel on `dietpi-update`? I guess too risky and might break custom setups that depend on current kernel. So at least should be only optional...

**Comment by MichaIng** [comment] 2019-03-02 22:37
I guess the issue has been resolved with the new images. I mark this as closed for now, but feel free to reopen if required.

If this is really kernel related, I see no chance that we can automate a fix via update. This has to be done manually to assure no unexpected issues occur, or, at best flash the new image.

**Comment by hekigan** [comment] 2019-04-26 02:12
Hi!
I see that this thread is closed but I encounter the same issue.
Yesterday I received the Tinker Board S and did a fresh install.

From LXDE I  start Chromium, it shows and closes back right away...

Just as an extra info, when installing, I got a 404 when trying to get some data from the Fourdee repo. Not sure if could be related in any way though.

**Comment by MichaIng** [comment] 2019-04-27 17:21
@hekigan 
> Just as an extra info, when installing, I got a 404 when trying to get some data from the Fourdee repo. Not sure if could be related in any way though.

I just went through the things we download from dietpi.com and one thing is: https://dietpi.com/downloads/binaries/asus/ASUSTB_GPU.7z
If this failed, then I expect Chromium fails. On the other hand LXDE fails then as well as whole Xserver most likely.
Can you please paste: `dpkg -l xserver-xorg-core`

Ah and did you install LDXE independently before or both in the same DietPi-Software run?

**Comment by hekigan** [comment] 2019-04-27 17:46
I did the install as a fresh install and both on the same run.
Since then I used the tip above to install an older version of chromium to make it work.

Below the result of your query:

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
hi  xserver-xorg-c 2:1.19.3-1   armhf        Xorg X server - core server
```

**Comment by MichaIng** [comment] 2019-05-01 07:56
@hekigan 
Okay actually I believe this has not yet finally resolved, although @Fourdee said
> Confirmed Chromium under autostart support

The `xserver-xorg-core` is at least what it should be, so ASUSTB_GPU.7z above got downloaded and installed successfully.

I will reopen the issue now. Which version of Chromium does work for you?

**Comment by MichaIng** [comment] 2019-06-08 14:29
@Stogoh 
Could you please try out the following:
```
cd /tmp
wget https://dietpi.com/downloads/binaries/asus/testing/ASUSTB_GPU.7z
7zr x ASUSTB_GPU.7z
rm ASUSTB_GPU.7z
apt-mark unhold xserver-common xserver-xorg-core
dpkg -i *.deb
G_AGF
apt-mark hold xserver-common xserver-xorg-core
```

**Comment by stogoh** [comment] 2019-06-08 15:09
> @Stogoh
> Could you please try out the following:
> 
> ```
> cd /tmp
> wget https://dietpi.com/downloads/binaries/asus/testing/ASUSTB_GPU.7z
> 7zr x ASUSTB_GPU.7z
> rm ASUSTB_GPU.7z
> apt-mark unhold xserver-common xserver-xorg-core
> dpkg -i *.deb
> G_AGF
> apt-mark hold xserver-common xserver-xorg-core
> ```

@MichaIng 
I've done it. Chromium is still working.

BTW: I had to enter `G_SUDO` before executing `G_AGF`

**Comment by MichaIng** [comment] 2019-06-08 15:13
@Stogoh 
> I've done it. Chromium is still working.

Good so far, would be great if you could test it with the new(est) Chromium version.

> BTW: I had to enter G_SUDO before executing G_AGF

Jep expected of course 🙂.

**Comment by stogoh** [comment] 2019-06-08 15:23
Well. I updated chromium from version `67.0.3396.87` to `72.0.3626.122` and it's not working again. Chromium just flashes white for a bit. I've also executed G_AGF command again. Still not working.

**Comment by MichaIng** [comment] 2019-06-08 15:29
@Stogoh 
To verify image and kernel version:
```
cat /etc/armbian_version
uname -a
```

> I've also executed G_AGF command again. Still not working.

This is btw just to let APT automatically install dependency packages after using `dpkg -i` to install packages manually.

**Comment by stogoh** [comment] 2019-06-08 21:19
### "Uname -a" outputs:
`Linux Barfritz 4.4.103+ #1 SMP Fri Jun 22 16:14:49 CST 2018 armv7l GNU/Linux`

**Comment by MichaIng** [comment] 2019-06-09 14:10
@Stogoh 
Ah it looks like you use an old TinkerOS based image. The new one is based on ARMbian which ships a new mainline based kernel, which might have the required support, not sure. Sadly AFAIK it is not possible or at least difficult to migrate to ARMbian kernel + bootloader basis, so either you need to reflash or of course stay with the older Chromium version, which should not be that bad.

But I will keep the issue open to see if other ATB users with the new image run into the same issue.

Thanks for testing the new graphics+xorg packages btw. which do not solve the issue sadly but do not hurt as well and ship a slightly enhanced media feature support + newer library versions.

**Comment by MichaIng** [comment] 2019-09-03 00:05
I mark this issue as closed. New Buster image is up. Tester required for GPU acceleration support: https://github.com/MichaIng/DietPi/issues/3094

**Closed as completed by MichaIng** 2019-09-03 00:05 UTC
Labels: Bug :lady_beetle:, NoFix, Stretch, ASUS Tinker Board
