### ISSUE TITLE
Mopidy python2 and Iris

### ISSUE THREAD

**Issue by lupa18** [MichaIng/DietPi#3485] opened 2020-04-22 02:45 UTC
#### Is your feature request related to a problem? Please describe:
When installing mopidy, you are using python2 and several plugins, like Iris, Spotify and other seems not to be working installing with v2. 

#### Describe the solution you'd like:
Is it possible to install/use mopidy with pyhton3?

**Comment by lupa18** [comment] 2020-04-22 02:49
And also having this warning:
"DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020...."

**Comment by MichaIng** [comment] 2020-04-22 08:32
@lupa18 
Many thanks for your report. Indeed I just checked and we install extensions with `pip` command instead of `pip3`. I see now this is new since Mopidy 3. Hmm, the problem is on ARMv8 we pull the Debian repo packages, since official Mopidy repo does not ship ARMv8 packages, hence we need to use the correct pip/pip3 based on arch and distro version 🤔.

**Comment by MichaIng** [comment] 2020-04-22 11:57
**Fixed with: #3486**

Note that new plugins need to be installed with `pip3` command or `python3 -m pip`, else those will be available for Python2 only.

**Closed as completed** 2020-05-03 22:17 UTC
Labels: Bug :lady_beetle:, Solution available :clinking_glasses:, Buster
