### ISSUE TITLE
Cannot set shairport-sync name attribute

### ISSUE THREAD

**Issue by vd** [MichaIng/DietPi#950] opened 2017-05-11 20:38 UTC
When I set the name attribute of the shairport reciever in /etc/shairport-sync.conf it is not reflected  when restarting all services with `dietpi-services restart`

**Comment by Fourdee** [comment] 2017-05-12 11:06
@vd 
Confirmed:
```
name = "Front Room";
```

Has no effect.

I believe its because we built Shairport-sync with avahi. When changing the hostname of the DietPi system, this also effects the shairport-sync name.

Please try changing the hostname:
```dietpi-config``` > Security Options > Change Hostname.

**Comment by Fourdee** [comment] 2017-05-24 11:46
@vd 

```name=``` having no effect will be fixed in v151:
https://github.com/Fourdee/DietPi/issues/962#issuecomment-301735237

```/usr/local/etc/shairport-sync.conf``` is the correct location for shairport-sync config.

I'll mark this as closed.

**Closed as completed by Fourdee** 2017-05-24 11:46 UTC
Labels: Question :grey_question:
