### ISSUE TITLE
DietPi-Software | Docker - Error while installing

### ISSUE THREAD

**Issue by Legion07** [MichaIng/DietPi#4845] opened 2021-10-16 09:23 UTC
#### Details:
- Date           | Sat Oct 16 10:21:12 BST 2021
- Bug report     | 4bfb7d7d-d30e-42ae-9771-b366d26259c9
- DietPi version | v7.6.2 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | From scratch
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 5.10.63-v8+ #1459 SMP PREEMPT Wed Oct 6 16:42:49 BST 2021 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `apt-get -qq --allow-change-held-packages install docker-ce`
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:

1. ...
2. ...
#### Expected behaviour:

- ...
#### Actual behaviour:

- ...
#### Extra details:

- ...
#### Additional logs:
```
Setting up docker-ce (5:20.10.9~3-0~debian-bullseye) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2021-10-16 10:21:12 BST; 15ms ago
TriggeredBy: ● docker.socket

**Comment by Joulinar** [comment] 2021-10-16 12:46
Could you share following pls

`journalctl -u docker`

**Comment by MichaIng** [comment] 2021-11-04 19:51
Marking as closed due to outstanding reply. Feel free to reopen if required.

**Closed by MichaIng** 2021-11-04 19:51 UTC
Labels: Waiting for user reply :hourglass_flowing_sand:, Investigation required :thinking:

**Comment by LightD31** [comment] 2021-11-06 12:16
I have the same problem here
#### Details:
- Date           | Sat Nov  6 12:07:16 GMT 2021
- Bug report     | 3ad5bf7a-f9f0-4588-816e-887ddc25bbc8
- DietPi version | v7.7.3 (MichaIng/master)
- Image creator  | DietPi Core Team
- Pre-image      | From scratch
- Hardware       | RPi 4 Model B (aarch64) (ID=4)
- Kernel version | `Linux DietPi 5.10.52-v8+ #1441 SMP PREEMPT Tue Aug 3 18:14:03 BST 2021 aarch64 GNU/Linux`
- Distro         | bullseye (ID=6,RASPBIAN=0)
- Command        | `apt-get -qq --allow-change-held-packages dist-upgrade`
- Exit code      | 100
- Software title | DietPi-Software
#### Steps to reproduce:
1. Try to install Docker, docker container or Portainer
#### Expected behaviour:
- Docker should be installed
#### Actual behaviour:
A error is happening
#### Extra details:
Seems specific to Rpi4 
#### Additional logs:
```
Setting up docker-ce (5:20.10.10~3-0~debian-bullseye) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2021-11-06 12:07:15 GMT; 19ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 15082 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 15082 (code=exited, status=1/FAILURE)
        CPU: 298ms
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
---------------------------------------------------------------------

**Comment by LightD31** [comment] 2021-11-06 12:19
> Could you share following pls
> 
> ```shell
> journalctl -u docker -u containerd
> ```
[log.txt](https://github.com/MichaIng/DietPi/files/7490426/log.txt)

**Comment by MichaIng** [comment] 2021-11-06 13:14
```
Nov 06 11:52:24 DietPi dockerd[12906]: time="2021-11-06T11:52:24.246797598Z" level=error msg="failed to mount overlay: no such device" storage-driver=overlay2
Nov 06 11:52:24 DietPi dockerd[12906]: time="2021-11-06T11:52:24.246953223Z" level=error msg="exec: \"fuse-overlayfs\": executable file not found in $PATH" storage-driver=fuse-overlayfs
Nov 06 11:52:24 DietPi dockerd[12906]: time="2021-11-06T11:52:24.251820466Z" level=error msg="AUFS was not found in /proc/filesystems" storage-driver=aufs
Nov 06 11:52:24 DietPi dockerd[12906]: time="2021-11-06T11:52:24.258037284Z" level=error msg="failed to mount overlay: no such device" storage-driver=overlay
```
It seems to not find any overlay driver.

I see that your kernel is not up-to-date. Was there probably a kernel upgrade and you still need to reboot to load it?
```
uname -r
ls -l /lib/modules
```
The versions shown in those two commands need to match, else no new kernel module (including filesystem drivers) can be loaded.
