### ISSUE TITLE
please update tasmoadmin 

### ISSUE THREAD

**Issue by Boebbele** [MichaIng/DietPi#6805] opened 2023-12-15 15:47 UTC
Dietpi-Software [27] Tasmoadmin

It installs an old Version v3.2.0 
Newest release is 3.3.0.

The intern self update funktion in tasmoadmin v3.2.0 Webinterface dont work.

Error: 
```
Warning: Undefined array key "release_url" in /var/www/tasmoadmin/pages/selfupdate.php on line 20

Warning: Undefined array key "latest_tag" in /var/www/tasmoadmin/pages/selfupdate.php on line 20

Fatal error: Uncaught TypeError: TasmoAdmin\SelfUpdate::update(): Argument #1 ($releaseUrl) must be of type string, null given, called in /var/www/tasmoadmin/pages/selfupdate.php on line 20 and defined in /var/www/tasmoadmin/src/SelfUpdate.php:28 Stack trace: #0 /var/www/tasmoadmin/pages/selfupdate.php(20): TasmoAdmin\SelfUpdate->update() #1 /var/www/tasmoadmin/index.php(66): include('...') #2 /var/www/tasmoadmin/index.php(111): render_template() #3 {main} thrown in /var/www/tasmoadmin/src/SelfUpdate.php on line 28
```

**Comment by MichaIng** [comment] 2023-12-15 16:11
It works well here:
```console
# curl -sSfL 'https://api.github.com/repos/TasmoAdmin/TasmoAdmin/releases/latest' | mawk -F\" '/^ *"browser_download_url": ".*\/tasmoadmin_v[^"\/]*\.tar\.gz"$/{print $4}'
https://github.com/TasmoAdmin/TasmoAdmin/releases/download/v3.3.0/tasmoadmin_v3.3.0.tar.gz
```
I guess the GitHub API was offline when you installed TasmoAdmin, and `dietpi-software` should have printed a block of `[FAILED]` informing you that obtaining the latest version failed and v3.2.0 was used as fallback, the latest known version when DietPi v8.24 was released.

**Comment by Boebbele** [comment] 2023-12-15 16:41
Strange...
I did an "dietpi-software reinstall 27"
And yet it is tasmoadmin v3.2.0 installed and no 3.3.0

![Screenshot_20231215-173906_Iodé Browser](https://github.com/MichaIng/DietPi/assets/77356505/f69e46ff-1e81-4d0e-9cbf-20d9fffd0dd8)

**Comment by MichaIng** [comment] 2023-12-15 16:47
Ah right, a reinstall won't update TasmoAdmin due to the existence of the web updater. The web updater does still not work?

**Comment by Boebbele** [comment] 2023-12-15 16:52
Yes the webupdater dont work.

**Comment by Boebbele** [comment] 2023-12-15 16:53
![Screenshot_20231215-175247_Iodé Browser](https://github.com/MichaIng/DietPi/assets/77356505/d86cf30c-cd1c-49c9-b2d3-3293db871e1c)

**Comment by Boebbele** [comment] 2023-12-15 17:01
I uninstalled tasmoadmin with dietpi-software and installed it again.
Yet i have 3.3.0

But the self webupdater dont work. Same errorlog (Screenshot)

**Comment by MichaIng** [comment] 2023-12-15 17:02
I am currently trying to replicate the error.

**Comment by MichaIng** [comment] 2023-12-15 17:08
Hmm, the web updater worked well here:
![image](https://github.com/MichaIng/DietPi/assets/28480705/031ef6b1-6507-4186-b277-b1478835cb66)
![image](https://github.com/MichaIng/DietPi/assets/28480705/3c6a2bf9-2afb-42e7-8bfe-5cca69422f0d)

There is a setting where the URL of the TasmoAdmin server needs to be set:
![image](https://github.com/MichaIng/DietPi/assets/28480705/73dbafd8-9d5c-4e14-bd5a-1825331eae27)

It seems the browser/client does a dedicated request to trigger the update. So if you try this from outside your LAN, the default entry (IP) might not be correct. Or does this show the public hostname, based on the request hostname, automatically?

**Comment by Boebbele** [comment] 2023-12-15 17:16
the IP addresses fit. tasmoadmin runs on a headless device local in my LAN. no remote access.

**Comment by Boebbele** [comment] 2023-12-15 17:18
![Screenshot_20231215-181801_Iodé Browser](https://github.com/MichaIng/DietPi/assets/77356505/4289fa9f-8cdf-48f0-8f55-3a6b18f77fba)

**Comment by Boebbele** [comment] 2023-12-15 18:08
i have additionally installed Homer and baikal an lighthtpd is everything on port 80. is that the problem?

**Comment by MichaIng** [comment] 2023-12-16 15:30
Ah, I could reproduce it with Lighttpd! A new problem with the rewrites. Found and solved the issue:
- I was expecting that rewrites require path elements passed to the backend, like `/tasmoadmin/selfupdate => /tasmoadmin/index.php/selfupdate`.
- We already recognised previously that this rewrite causes issues with Lighttpd, since it has no way to pass FastCGI variables to tell the backend that `/tasmoadmin` is still the base path. So the backend then produces asset URLs like `/tasmoadmin/index.php/resources/css/style.css`, which of course does not exist, so pages load without styles, images and scripts. Apache2 and Nginx do this automatically, respectively have ways to tell the backend about which part is the base path to generate other URLs from.
- What worked with all other pages is to just append everything as query string: `/tasmoadmin/selfupdate => /tasmoadmin/index.php?selfupdate`. I was already wondering about this, since this did not happen in the Nginx config they use for their Docker image: https://github.com/TasmoAdmin/TasmoAdmin/blob/master/.docker/rootfs/etc/nginx/nginx.conf
- I actually thought that path elements are implied in the `$args` parameter, but rereading the docs and testing turns out this really is the query string only, while the path is completely omitted in the rewrite. I first did not understand how this can even work, but it is simple: The backend takes the path/route from the original request URL, which is always passed, instead of from the rewrite URL. So the rewrite URL must only contain `/tasmoadmin/index.php`, in case appended with the query string (rarely or not used by TasmoAdmin), and no path needs to be part of that rewrite URL.

Fixed with: https://github.com/MichaIng/DietPi/commit/b345081

Please update your config like this:
```sh
curl -sSfo /etc/lighttpd/conf-available/99-dietpi-tasmoadmin.conf 'https://raw.githubusercontent.com/MichaIng/DietPi/dev/.conf/dps_27/lighttpd.tasmoadmin.3.conf'
systemctl restart lighttpd
```

**Comment by Boebbele** [comment] 2023-12-16 16:21
It works! You are the best! Thank you very much!

**Closed as completed** 2023-12-17 23:49 UTC
Labels: Bug :lady_beetle:, Solution available :clinking_glasses:
