### ISSUE TITLE
Dietpi pihole orange pi one not fully installing

### ISSUE THREAD

**Issue by newdietpi** [MichaIng/DietPi#984] opened 2017-05-28 17:38 UTC
Install pihole via dietpi on the orange pi one doesn't fully install. Two steps I noticed missing was the setup web interface and either the screen before/after it. Installing via curl works.

**Comment by Fourdee** [comment] 2017-05-29 13:17
@newdietpi 

Thanks for the report 👍 

> Installing via curl works.

Our installation uses the same installer:  http://install.pi-hole.net. However, we use ```wget``` (which is installed by default on all DietPi systems):
https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L4172-L4195

---

> Install pihole via dietpi on the orange pi one doesn't fully install. Two steps I noticed missing was the setup web interface and either the screen before/after it. 

Unable to replicate this in our tests.

- Did you see the following prompt during install?
![image](https://cloud.githubusercontent.com/assets/7077026/26551163/081dda0e-4479-11e7-92e4-7857f721c5cc.png)

If not, and no prompt was displayed regarding "ERROR: URL offline", issue could be caused by:
- freak loss of connection either at your end or http://install.pi-hole.net during the ```wget``` process.
-  http://install.pi-hole.net script was temporarily "broken", and is now fixed.
- underlying hardware/instability issue with your OPi one.

**Comment by newdietpi** [comment] 2017-05-29 15:15
I replicated the error again last night with a fresh install of dietpi.

I noticed if you select to install pi-hole during the initial dietpi setup vs installing it after it is hit or miss.

I believe it's a combination of the following.

You have to choose not to install pi-hole during the initial dietpi setup then install pi-hole from dietpi afterwards which may work. I was able to get this working one time since I could login via /pihole instead of /admin.
Second time didn't work. I installed pi-hole during the initial dietpi setup, which didn't work. Uninstalled then installed which did via dietpi. Was able login using /pihole
Third time I did the same as the second but used curl which worked.

I think something in the initial setup doesn't fully install pihole?

**Comment by newdietpi** [comment] 2017-05-29 15:18
It's not as smooth installing it on the opi one vs my rpi3 for some reason, I can install it during the initial dietpi everytime on my rpi3 whereas I have to do the above with my opi one

**Comment by newdietpi** [comment] 2017-05-29 15:25
Can you activate newpi on dietpi forums? I had to go on reddit to get help then they pointed me here to report my issue.

**Comment by Fourdee** [comment] 2017-05-29 17:25
@newdietpi 

> You have to choose not to install pi-hole during the initial dietpi setup then install pi-hole from dietpi afterwards which may work. I was able to get this working one time since I could login via /pihole instead of /admin.
Second time didn't work. I installed pi-hole during the initial dietpi setup, which didn't work. Uninstalled then installed which did via dietpi. Was able login using /pihole
Third time I did the same as the second but used curl which worked.

Thanks for the info 👍 
I'll try to duplicate your tests and see if we can find the cause.

**Closed as completed** 2017-05-31 04:29 UTC
Labels: NoFix, Not a DietPi issue
