### ISSUE TITLE
Provide VMX appliance for ARM arch

### ISSUE THREAD

**Issue by bbugh** [MichaIng/DietPi#6615] opened 2023-09-12 19:21 UTC
### Creating a feature request

Hi 👋, thanks for the great project. Sorry if this is the wrong template, it wasn't clear which one to use for this request.

#### Is your feature request related to a problem? Please describe:

VMX appliance was added in https://github.com/MichaIng/DietPi/issues/5431 which is awesome! But it's only for x86_64. Attempting to import this into Parallels on a Mac M1/M2 arm64 arch of course fails.

#### Describe the solution you'd like:

A vmx build (arm64?) that will work on ARM Macs.

#### Describe alternatives you've considered:

Not having it 😢

#### Additional context

- ...

**Comment by MichaIng** [comment] 2023-09-12 19:52
Let me close this as duplicate of this request: #5637

**Closed as completed by MichaIng** 2023-09-12 19:52 UTC
Labels: Duplicate
